// ****************************************************************************
// enums.h
// 
// 
// ****************************************************************************

#ifndef _ENUM_H_
#define _ENUM_H_

enum EATTR 
{
	EATTR_DEFAULT,
	EATTR_SPATIAL,
	EATTR_PHYSIC,
	EATTR_GEOM,
	EATTR_TEXTURE,
	EATTR_STATE,
	EATTR_HP,
	EATTR_COLOR,
	EATTR_DROP,
	EATTR_TYPE
};

enum ECOMP
{
	ECOMP_DEFAULT,
	ECOMP_RENDER,
	ECOMP_RENDER_TEXT,
	ECOMP_PHYSIC,
	ECOMP_COLLISION,
	ECOMP_DAMAGEABLE,
	ECOMP_DROP,
	ECOMP_HUD_HP,
	ECOMP_ANIM,
	ECOMP_AI,
	ECOMP_SLIME_AI,
	ECOMP_ENEMY_AI
};

enum EMSG
{
	EMSG_DEFAULT,
	EMSG_RENDER,
	EMSG_RENDER_FOREGROUND,
	EMSG_RENDER_BACKGROUND,
	EMSG_RENDER_HUD,
	EMSG_THINK,
	EMSG_SPATIAL,
	EMSG_PHYSIC,
	EMSG_COLLISION,
	EMSG_KEYBOARD,
	EMSG_STATE,
	EMSG_DROP,
	EMSG_DAMAGE,
	EMSG_DIE,
	EMSG_CHANGEANIM
};

enum GEOM
{
	GEOM_SQUARE,
	GEOM_TRIANGLE
};	

enum COLOR
{
	COLOR_RED,
	COLOR_GREEN,
	COLOR_BLUE,
	COLOR_ORANGE,
	COLOR_PURPLE,
	COLOR_YELLOW,
	COLOR_WHITE,
	COLOR_BLACK,
	COLOR_FIRST = COLOR_RED,
	COLOR_LAST = COLOR_BLACK
};	

enum ANIM
{
	ANIM_STILL,
	ANIM_WALKING,
	ANIM_PREJUMP,
	ANIM_JUMP,
	ANIM_LANDING,
	ANIM_ATTACK,
	ANIM_DIE,
	ANIM_FIRST = ANIM_STILL,
	ANIM_LAST = ANIM_DIE
};

enum LOGGER_FIELDS
{
	LOGGER_EATTR_DEFAULT,
	LOGGER_EATTR_SPATIAL,
	LOGGER_EATTR_PHYSIC,
	LOGGER_EATTR_GEOM,
	LOGGER_EATTR_TEXTURE,
	LOGGER_EATTR_STATE,
	LOGGER_EATTR_HP,
	LOGGER_EATTR_COLOR,
	LOGGER_EATTR_DROP,
	LOGGER_EATTR_TYPE,
	
	LOGGER_ECOMP_DEFAULT,
	LOGGER_ECOMP_RENDER,
	LOGGER_ECOMP_RENDER_TEXT,
	LOGGER_ECOMP_PHYSIC,
	LOGGER_ECOMP_COLLISION,
	LOGGER_ECOMP_DAMAGEABLE,
	LOGGER_ECOMP_DROP,
	LOGGER_ECOMP_HUD_HP,
	LOGGER_ECOMP_ANIM,
	LOGGER_ECOMP_AI,
	LOGGER_ECOMP_SLIME_AI,
	LOGGER_ECOMP_ENEMY_AI
	
};

#endif